config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'page/home'
  root to: 'pages#home'
  resources :products do
    resources :warranties do
      resources :returns do
        resources :messages
      end

    end
  end
get '/.well-known/brave-rewards-verification.txt', to: static('brave-rewards-verification.txt')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :products
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :return
  belongs_to :user
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :manufacturer
  belongs_to :category
  # adding a photouploader for product creation
  mount_uploader :photo, PhotoUploader

end

app/models/return.rb
class Return < ApplicationRecord
  belongs_to :warranty
  validates :comment, length: { minimum: 10 }, presence: { message: "A short reason is necessary given please" }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :warranties
  # need to update the model so that the app policy can associate the records of return with a user
  has_many :returns, through: :warranties
end

app/models/warranty.rb
class Warranty < ApplicationRecord
  belongs_to :user
  belongs_to :product
  # adding a photouploader for warranty proof of purchase (picture or pdf) creation
  mount_uploader :photo, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Protect applications from CSRF vulnerability.
  protect_from_forgery with: :exception
  # all the application views require that the user be logged in except
  # indexes and/or decided otherwiser in the controllers
  before_action :authenticate_user!, :except => [:index]
  # Manage/tune access right / policies with Pundit Gem
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # catch a authorization error (user should not be able to access)

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # behavior is an alert flash and a redirect to Homepage
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_return, only: [:index, :show, :new, :create, :edit, :update]
  before_action :authenticate_user!

  def index
    @messages = Message.find_by(:return_id)
  end

  def show
  end

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    @message.user_id = current_user.id
    @message.return_id = @return.id
    if @message.save
      redirect_to product_warranty_return_path(@product, @warranty, @return)
    else
      render :new
    end

  end

private
  def set_return
    @return = Return.find(params[:return_id])
    @warranty = Warranty.find(params[:warranty_id])
    @product = Product.find(params[:product_id])
  end

  def message_params
    params.require(:message).permit(:content)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update]
  before_action :authenticate_user!, :except =>  [:index, :show]
  def index
    @products = policy_scope(Product)
  end

 def create
    @product = Product.new(product_params)
    authorize @product
    if @product.save
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  def show
    @category = Category.find(@product.category_id)
    @manufacturer = Manufacturer.find(@product.manufacturer_id)
  end

  def new
    @product = Product.new
    authorize @product
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to product_path(@product)
  end

  def destroy
  end

  private

  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def product_params
    params.require(:product).permit(:ean,
      :asin,
      :product_name,
      :manufacturer_id,
      :category_id,
      :photo)
  end

end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_warranty, only: [:new, :create, :show, :edit, :update, :destroy]
  before_action :set_return, only: [:show, :edit, :update, :destroy]

  def new
    @return = Return.new()
    authorize @return
  end

  def create
    @return = Return.new(return_params)
    authorize @return
    @return.warranty_id = @warranty.id
    if @return.save
      redirect_to  product_warranty_return_path(@product, @warranty, @return)
    else
      render :new
    end
  end

  def show
    @messages = Message.where(return_id: @return.id)
  end

  def edit
    @messages = Message.where(return_id: @return.id)
  end

  def update
    @return.update(return_params)
    redirect_to  product_warranty_return_path(@product, @warranty, @return)
  end

  def destroy
  end

private
    def set_warranty
      @warranty = Warranty.find(params[:warranty_id])
      @product = Product.find(params[:product_id])
      @category = Category.find(@product.category_id)
      @manufacturer = Manufacturer.find(@product.manufacturer_id)
    end


    def set_return
      @return = Return.find(params[:id])
      authorize @return
    end

    def return_params
      params.require(:return).permit(:status, :comment)
    end
end

app/controllers/warranties_controller.rb
class WarrantiesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_warranty, only: [:show, :edit, :update]
  before_action :set_product, only: [:new, :create, :show, :update, :destroy]

  def index
  end


  def new
    @warranty = Warranty.new
    authorize @warranty
  end

  def create
    @warranty = Warranty.new(warranty_params)
    authorize @warranty
    @warranty.product_id = @product.id
    @warranty.end_date = @warranty.begin_date + 365*2
    @warranty.user_id = current_user.id
    # authorize @warranty
    if @warranty.save
      redirect_to product_warranty_path(@product, @warranty)
    else
      render :new
    end
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
  end

  private
    def set_warranty
      @warranty = Warranty.find(params[:id])
      authorize @warranty
      @product = Product.find(params[:product_id])
      @category = Category.find(@product.category_id)
      @manufacturer = Manufacturer.find(@product.manufacturer_id)
    end

    def set_product
      @product = Product.find(params[:product_id])
    end


    def warranty_params
      params.require(:warranty).permit(:begin_date, :photo )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

      <meta name="robots" content="noindex, nofollow">
       <title>Warrantize : get your reverse logistic organized</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/messages/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Message#edit</h1>
    <p>Find me in app/views/messages/edit.html.erb</p>
  </div>
</div>

app/views/messages/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Messages#index</h1>
    <p>Find me in app/views/messages/index.html.erb</p>
  </div>
</div>

app/views/messages/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Messages#new</h1>
    <p>Find me in app/views/messages/new.html.erb</p>
    <div class="commenting-form">
      <%= simple_form_for  [@product, @warranty, @return, @message] do |f| %>
        <div class="form-inputs checkout">
          <div class="form-group">
            <%= f.input :content,
                                    as: :text,
                                    label: "Message" %>
          </div>
        <div class="form-actions text-center">
            <%= f.button :submit, "add a message", class: " btn btn-flat" %>
        </div>
      </div>
        <% end %>
    </div>
  </div>
</div>

app/views/messages/show.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Messagre New  </h1>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(
<%= image_path("warantize.png") %>
);">
  <div class="container">
    <h1>Warrantize !</h1>
    <p>Get your reverse logistic Organized !</p>
    <%= link_to "Try it now", products_path, class: " btn btn-flat" %>


  </div>
</div>
<!-- faire des cartes  -->
<div class="spacer"></div>
<div class="container">
  <div class="row">
    <div class="col-sm-4">
      <div class="card-trip">
        <img src="https://images.unsplash.com/photo-1518135714426-c18f5ffb6f4d?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2573&q=80">
        <div class="card-trip-infos">
          <div>
            <h2>Improve your brand loyalty</h2>
            <p>Give your clients a proper vision of your process from their initial request till the resolution</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card-trip">
        <img src="https://images.unsplash.com/photo-1531538512164-e6c51ea63d20?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2467&q=80">
        <div class="card-trip-infos">
          <div>
            <h2>Manage ressources efficiently</h2>
            <p>The process is clear and each step well documented. Employee and services knows exactly where to go next</p>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-4">
      <div class="card-trip">
        <img src="https://images.unsplash.com/photo-1526628953301-3e589a6a8b74?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=2495&q=80">
        <div class="card-trip-infos">
          <div>
            <h2>Get a better vision of your returns</h2>
            <p>Measures your main reverse logistic KPI in real time. </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Products#edit</h1>
    <%= simple_form_for @product do |f| %>
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <%= f.association :category , label_method: :category_name, value_method: :id, include_blank: false %>
      <%= f.association :manufacturer, label_method: :manufacturer_name, value_method: :id, include_blank: false %>
      <%= f.input :product_name, html: { autocomplete: 'off' }, class:"form-controls" %>
      <%= f.input :ean, html: { autocomplete: 'off' }, class:"form-controls" %>
      <%= f.input :asin %>
      <%= f.input :photo, class:"form-controls btn-form" %>
      <%= f.input :photo_cache, as: :hidden %>
       <%= f.button :submit, class: 'btn btn-flat' %>











    <% end %>
  </div>
</div>

app/views/products/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Products#index</h1>
    <p>Find me in app/views/products/index.html.erb</p>

    <% @products.each  do |product|  %>
      <p> <%= product.product_name %>   <%= link_to "upload my warranty" , new_product_warranty_path(product.id) , class: " btn btn-flat"  %>

        <% if not product.asin.empty? %>
          <%= link_to "buy again on amazon" , "https://www.amazon.fr/dp/#{product.asin}/ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=warrantize04-21&language=fr_FR", class: " btn btn-flat"   %>
        <% end %>

        <% if policy(Product).edit? %>
          <%= link_to "update product", edit_product_path(product.id), class: " btn btn-flat"  %>
        <% end %>

         <%= link_to "view product", product_path(product.id), class: " btn btn-flat"  %>


    </p>
    <% end %>
   <h2>Not seeing yours ? </h2>
   <div><%= link_to "Add it now " , new_product_path , class: " btn btn-flat"  %></div>
  </div>
</div>

app/views/products/new.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Products#new</h1>
    <p>Find me in app/views/products/new.html.erb</p>
    <div class="row">

    <!--  find a way to have list with manufacturer (brand) and product cateogy
      t.bigint "manufacturer_id"
      t.bigint "category_id"
    -->

      <%= simple_form_for @product do |f| %>
                <%= f.error_notification %>
                <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
                <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <%= f.association :category , label_method: :category_name, value_method: :id, include_blank: false %>
                    </div>
                  </div>
                </div>
                 <div class="row">
                  <div class="col-sm-6">
                    <div class="form-group">
                      <%= f.association :manufacturer, label_method: :manufacturer_name, value_method: :id, include_blank: false %>
                    </div>
                  </div>
                </div>

                  <div class="row">
                    <div class="col-sm-6">
                      <div class="form-group">
                        <%= f.input :product_name,
                                    html: { autocomplete: 'off' },
                                    class:"form-controls" %>
                      </div>
                    </div>
                  </div>
                  <div class="form-inputs">
                    <div class="row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <%= f.input :ean,
                                      html: { autocomplete: 'off' },
                                      class:"form-controls" %>
                        </div>
                      </div>
                    </div>
                     <div class="form-inputs">
                    <div class="row">
                      <div class="col-sm-6">
                        <div class="form-group">
                          <%= f.input :asin %>
                        </div>
                      </div>
                    </div>
                  <div class="form-group">
                    <%= f.input :photo,
                                class:"form-controls btn-form" %>
                  </div>
                  <%= f.input :photo_cache, as: :hidden %>

                </div>
                <div class="form-actions text-center">
                  <%= f.button :submit, class: 'btn btn-flat' %>
                </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="wrapper">
  <div class="container">
    <p>
    <%= cl_image_tag(@product.photo, width: 200) %>
    </p>
    <h1><%= @manufacturer.manufacturer_name %> - <%= @product.product_name %> </h1><small> <%= link_to 'edit', edit_product_path(@product)  %> </small>
    <p>EAN : <%= @product.ean %> </p>
    <p><%= @category.category_name %> </p>

    <%= link_to "upload my warranty" , new_product_warranty_path(@product), class: " btn btn-flat"   %>
    <% if not @product.asin.empty? %>
      <%= link_to "buy again on amazon" , "https://www.amazon.fr/dp/#{@product.asin}/ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=warrantize04-21&language=fr_FR", class: " btn btn-flat"   %>
    <% end %>
  </div>
</div>

app/views/returns/edit.html.erb
<div class="wrapper">
  <div class="container">
    <H1>Return Details</H1>
    <h2>Return</h2>
    <p><strong>Warranty expiration</strong> :  <%= @warranty.end_date %>  <br> <strong>  Return request made on</strong> : <%= @return.created_at %></p>
    <p>Initial Request : <%= @return.comment %></p>
    <p>Current Status : <%= @return.status  %></p>
    <h3> Update status</h3>
    <%= simple_form_for [@product, @warranty, @return] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
              <div class="form-group">
                <%= f.input :status,
                             priority: [ "New" ],
                             collection: [ "New", "Rejected", "Accepted"] %>
              </div>
            </div>
          </div>
        <div class="form-actions text-center">
          <%= f.button :submit, class: " btn btn-flat"  %>
        </div>
        <% end %>


    <h2>Product</h2>
    <p>
    <%= cl_image_tag(@product.photo, width: 200) %>
    </p>
    <h3><%= @manufacturer.manufacturer_name %> - <%= @product.product_name %> </h3>
    <p>EAN : <%= @product.ean %> </p>
    <p><%= @category.category_name %> </p>






  </div>
</div>

app/views/returns/new.html.erb
<div class="wrapper">
  <div class="container">
        <div class="text-center">
          <h1>Return your product</h1>
        </div>

        <%= simple_form_for [@product, @warranty, @return] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
              <div class="form-group">
                <%= f.input :comment,
                              as: :text,
                              label: "What is wrong with the product? " %>
              </div>
              <div class="form-group hidden">
                <%= f.input :status,
                              as: :string,
                              label: "status",
                              placeholder: "new",
                              input_html: {value: "new"}
                               %>
              </div>
            </div>
          </div>
        <div class="form-actions text-center">
          <%= f.button :submit, class: " btn btn-flat"  %>
        </div>
        <% end %>
        </div>
        <div class="text-center">
          <%= link_to "Revenir à la liste", root_path %>
        </div>

    </div>
  </div>
</div>

app/views/returns/show.html.erb
<div class="wrapper">
  <div class="container">
    <H1>Return Details</H1>
    <p><strong>Warranty expiration</strong> :  <%= @warranty.end_date %>  <br> <strong>  Return request made on</strong> : <%= @return.created_at %></p>
    <p>Return Status : <%= @return.status  %> <%= link_to  "edit", edit_product_warranty_return_path(@return)  %></p>
    <h2>messages</h2>
    <p> Initial Request : <%= @return.comment %></p>

    <% @messages.each do |m| %>
      <p><%= m.content %></p>
    <% end %>


    <h4>Product</h4>
<!--     <p>
 -->
  <% # cl_image_tag(@product.photo, width: 200) %>
 <!--     </p>
 -->    <h3><%= @manufacturer.manufacturer_name %> - <%= @product.product_name %> </h3>
    <p>EAN : <%= @product.ean %> </p>
    <p><%= @category.category_name %> </p>






  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/warrantize" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://twitter.com/warrantize_co" target="_blank"><i class="fab fa-twitter"></i></a>
    <a href="https://www.linkedin.com/company/warrantize/" target="_blank"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> by Warrantize
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag("logo-warrantize.png") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <% if user_signed_in? %>
      <!-- user info for debug to delete later -->
      <li class="nav-item active">
        Admin: <%= current_user.admin %>

      </li>
      <li class="nav-item active">
        &nbsp; user.id: <%= current_user.id %>

      </li>

      <li class="nav-item active">
          <%= link_to "Home", root_path , class: "nav-link" %>

        </li>
        <li class="nav-item dropdown">
          <%= image_tag "user.svg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Catalog", products_path, class: "dropdown-item" %>
            <%= link_to "Warranty", "#", class: "dropdown-item" %>
            <%= link_to "Modify my account", edit_user_registration_path, class: "dropdown-item"  %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "Catalog", products_path, class: "nav-link" %>
      </li>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/warranties/edit.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Warranties#edit</h1>
    <p>Find me in app/views/warranties/edit.html.erb</p>
  </div>
</div>

app/views/warranties/index.html.erb
<div class="wrapper">
  <div class="container">
    <h1>Warranties#index</h1>
    <p>Find me in app/views/warranties/index.html.erb</p>
  </div>
</div>

app/views/warranties/new.html.erb
<div class="wrapper">
  <div class="container">
        <div class="text-center">
          <h1>Add a warranty</h1>
        </div>

        <%= simple_form_for [@product, @warranty] do |f| %>
        <%= f.error_notification %>
        <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class="form-inputs">
          <div class="row">
            <div class="col-sm-offset-3 col-sm-6">
              <div class="form-group">
                <%= f.input :begin_date,
                              as: :string,
                              input_html: {class: "datepicker"},
                              label: "Date of purchase" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-6">
              <div class="form-group">
                 <%= f.input :photo %>
                 <%= f.input :photo_cache, as: :hidden %>
              </div>
            </div>
          </div>

        <div class="form-actions text-center">
          <%= f.button :submit, class: " btn btn-flat"  %>
        </div>
        <% end %>
        </div>
        <div class="text-center">
          <%= link_to "Revenir à la liste", root_path %>
        </div>

    </div>
  </div>
</div>

app/views/warranties/show.html.erb
<div class="wrapper">
  <div class="container">
    <strong>Your Warranty</strong> :     <%= @warranty.id %></br>
    <strong>Started in</strong> : <%= @warranty.begin_date %></br>
    <strong>Ending in</strong> : <%= @warranty.end_date %></br>
    <p>
      <%= cl_image_tag(@product.photo, width: 200) %>
    </p>
    <h1><%= @manufacturer.manufacturer_name %> - <%= @product.product_name %> </h1>
    <p>EAN : <%= @product.ean %> </p>
    <p><%= @category.category_name %> </p>

    <%= link_to "Ask for a return " , new_product_warranty_return_path(@product, @warranty), class: " btn btn-flat"   %>
  </div>
</div>